//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassagePlanner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipInfo_ShipName {
            get {
                return ((string)(this["ShipInfo_ShipName"]));
            }
            set {
                this["ShipInfo_ShipName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipInfo_ShipOwner {
            get {
                return ((string)(this["ShipInfo_ShipOwner"]));
            }
            set {
                this["ShipInfo_ShipOwner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShipInfo_AverageSeaSpeed {
            get {
                return ((double)(this["ShipInfo_AverageSeaSpeed"]));
            }
            set {
                this["ShipInfo_AverageSeaSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShipInfo_DailyConsumptionHFO {
            get {
                return ((double)(this["ShipInfo_DailyConsumptionHFO"]));
            }
            set {
                this["ShipInfo_DailyConsumptionHFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShipInfo_DailyConsumptionGO {
            get {
                return ((double)(this["ShipInfo_DailyConsumptionGO"]));
            }
            set {
                this["ShipInfo_DailyConsumptionGO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShipInfo_ShipBeam {
            get {
                return ((double)(this["ShipInfo_ShipBeam"]));
            }
            set {
                this["ShipInfo_ShipBeam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipInfo_NavigationalBridgeWatchConditions {
            get {
                return ((string)(this["ShipInfo_NavigationalBridgeWatchConditions"]));
            }
            set {
                this["ShipInfo_NavigationalBridgeWatchConditions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipInfo_EcdisSystem {
            get {
                return ((string)(this["ShipInfo_EcdisSystem"]));
            }
            set {
                this["ShipInfo_EcdisSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShipInfo_BlockCoefficients {
            get {
                return ((string)(this["ShipInfo_BlockCoefficients"]));
            }
            set {
                this["ShipInfo_BlockCoefficients"] = value;
            }
        }
    }
}
