//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class activeRoute {
    
    private activeRouteRouteWp[] routeWpField;
    
    private string routeIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("routeWp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public activeRouteRouteWp[] routeWp {
        get {
            return this.routeWpField;
        }
        set {
            this.routeWpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string routeId {
        get {
            return this.routeIdField;
        }
        set {
            this.routeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class activeRouteRouteWp {
    
    private int wpPrimaryNumberField;
    
    private bool wpPrimaryNumberFieldSpecified;
    
    private int wpSecondaryNumberField;
    
    private bool wpSecondaryNumberFieldSpecified;
    
    private string wpTypeField;
    
    private double latAsDecimalDegreeField;
    
    private double longAsDecimalDegreeField;
    
    private string followingLegTypeField;
    
    private double resultingSpeedInKnotField;
    
    private bool resultingSpeedInKnotFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int wpPrimaryNumber {
        get {
            return this.wpPrimaryNumberField;
        }
        set {
            this.wpPrimaryNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool wpPrimaryNumberSpecified {
        get {
            return this.wpPrimaryNumberFieldSpecified;
        }
        set {
            this.wpPrimaryNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int wpSecondaryNumber {
        get {
            return this.wpSecondaryNumberField;
        }
        set {
            this.wpSecondaryNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool wpSecondaryNumberSpecified {
        get {
            return this.wpSecondaryNumberFieldSpecified;
        }
        set {
            this.wpSecondaryNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wpType {
        get {
            return this.wpTypeField;
        }
        set {
            this.wpTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double latAsDecimalDegree {
        get {
            return this.latAsDecimalDegreeField;
        }
        set {
            this.latAsDecimalDegreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double longAsDecimalDegree {
        get {
            return this.longAsDecimalDegreeField;
        }
        set {
            this.longAsDecimalDegreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string followingLegType {
        get {
            return this.followingLegTypeField;
        }
        set {
            this.followingLegTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double resultingSpeedInKnot {
        get {
            return this.resultingSpeedInKnotField;
        }
        set {
            this.resultingSpeedInKnotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultingSpeedInKnotSpecified {
        get {
            return this.resultingSpeedInKnotFieldSpecified;
        }
        set {
            this.resultingSpeedInKnotFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private activeRoute[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("activeRoute")]
    public activeRoute[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
